name: che-install

on: [push]

jobs:
  example:
    name: setup che
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.0
        with:
          minikube version: 'v1.11.0'
          kubernetes version: 'v1.18.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: |
          kubectl get nodes
          # minikube stop
          # minikube addons enable ingress
          # minikube start
          bash <(curl -sL  https://www.eclipse.org/che/chectl/)
          chectl server:start --platform=minikube --installer=helm
          
