name: che-install

on: [push]

jobs:
  example:
    name: setup che
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.0
        with:
          minikube version: 'v1.11.0'
          kubernetes version: 'v1.18.2'
          start args: '--addons=ingress'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: |
          echo "list nodes with kubectl"
          kubectl get nodes
          echo "get addons list"
          minikube addons list
          echo "change permissions"
          sudo -E chmod -R 777 "/etc/kubernetes/addons/"
          echo "check ingress"
          kubectl get pods -n ingress-nginx
          echo "wait 30s"
          sleep 30
          echo "check ingress again"
          kubectl get pods -n ingress-nginx
          echo "download chectl"
          bash <(curl -sL  https://www.eclipse.org/che/chectl/)
          echo "start chectl"
          chectl server:start --platform=minikube --installer=helm
          
