name: che-install

on: push

# on: #[push]

jobs:
  install:
    name: setup che
    runs-on: ubuntu-18.04
    steps:
      - name: Setup che
        uses: benoitf/che-install-gh-action@master
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check
        run: |
          echo "list nodes with kubectl"
          kubectl get nodes
