name: che-install
on: push

jobs:
  install:
    name: setup che
    runs-on: macos-10.15
    steps:
#      - name: Start SSH via Ngrok
#        run: curl -sL https://gist.githubusercontent.com/benoitf/7629eeb50382b8ea811a1ba4473c9b81/raw/0d3a545129cdf82c55ece6fa697efc2ad565cd2e/ngrok.txt  | bash
#        env:
#         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
#         USER_PASS: ${{ secrets.NGROK_PASS }}           
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install docker
        run: |
           brew install --cask docker
           # allow the app to run without confirmation
           xattr -d -r com.apple.quarantine /Applications/Docker.app

           # preemptively do docker.app's setup to avoid any gui prompts
           sudo /bin/cp /Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools

           # the plist we need used to be in /Applications/Docker.app/Contents/Resources, but
           # is now dynamically generated. So we dynamically generate our own
           sudo tee "/Library/LaunchDaemons/com.docker.vmnetd.plist" > /dev/null <<'EOF'
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
           	<key>Label</key>
           	<string>com.docker.vmnetd</string>
           	<key>Program</key>
           	<string>/Library/PrivilegedHelperTools/com.docker.vmnetd</string>
           	<key>ProgramArguments</key>
           	<array>
           		<string>/Library/PrivilegedHelperTools/com.docker.vmnetd</string>
           	</array>
           	<key>RunAtLoad</key>
           	<true/>
           	<key>Sockets</key>
           	<dict>
           		<key>Listener</key>
           		<dict>
           			<key>SockPathMode</key>
           			<integer>438</integer>
           			<key>SockPathName</key>
           			<string>/var/run/com.docker.vmnetd.sock</string>
           		</dict>
           	</dict>
           	<key>Version</key>
           	<string>59</string>
           </dict>
           </plist>
           EOF

           sudo /bin/chmod 544 /Library/PrivilegedHelperTools/com.docker.vmnetd
           sudo /bin/chmod 644 /Library/LaunchDaemons/com.docker.vmnetd.plist
           sudo /bin/launchctl load /Library/LaunchDaemons/com.docker.vmnetd.plist

           sleep 5
           open -g -a Docker.app
           # Wait for the server to start up, if applicable.
           i=0
           while ! docker system info &>/dev/null; do
            (( i++ == 0 )) && printf %s '-- Waiting for Docker to finish starting up...' || printf '.'
            sleep 1
           done
           (( i )) && printf '\n'
           echo "-- Docker is ready."
      - name: 'Docker docker.io Login'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Start minikube
        id: run-minikube
        uses: benoitf/setup-minikube-action@use-mac
        with:
          minikube-version: v1.20.0
      - name: Deploy Eclipse Che
        id: deploy-che
        uses: che-incubator/che-deploy-action@next
      - name: Run Happy Path tests
        id: run-happy-path-tests
        uses: che-incubator/happy-path-tests-action@next
        with:
          che-url: ${{ steps.deploy-che.outputs.che-url }}
      - name: upload artifacts
        if: ${{ always() }}
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: che/tests/e2e/report/
#      - name: Wait 1hour before shutting down instance
#        if: ${{ failure() }}
#        run: sleep 1h

