name: che-install
on: push
jobs:
  install:
    name: setup che
    runs-on: macos-10.15
    steps:
      - name: Start SSH via Ngrok
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
         USER_PASS: ${{ secrets.NGROK_PASS }}           
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install docker
        run: brew install --cask docker
      - name: 'Docker docker.io Login'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Start minikube
        id: run-minikube
        uses: benoitf/setup-minikube-action@use-mac
      - name: Deploy Eclipse Che
        id: deploy-che
        uses: che-incubator/che-deploy-action@next
      - name: Run Happy Path tests
        id: run-happy-path-tests
        uses: che-incubator/happy-path-tests-action@next
        with:
          che-url: ${{ steps.deploy-che.outputs.che-url }}
      - name: upload artifacts
        if: ${{ always() }}
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: che/tests/e2e/report/
#      - name: Wait 1hour before shutting down instance
#        if: ${{ failure() }}
#        run: sleep 1h
