name: che-install
on: push
jobs:
  install:
    name: setup che
    runs-on: ubuntu-20.04
    steps:
      - name: Start SSH via Ngrok
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
         USER_PASS: ${{ secrets.NGROK_PASS }}           
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Docker docker.io Login'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup che
        id: setup-che
        uses: benoitf/che-install-gh-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Custom che-Theia
        id: custom-che-theia
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: custom-devfile-deployment
            labels:
              app: customdevfile
          spec:
            selector:
              matchLabels:
                app: customdevfile
            template:
              metadata:
                labels:
                  app: customdevfile
              spec:
                containers:
                - name: customdevfile
                  image: docker.io/httpd:2.4.46-alpine
                  ports:
                  - containerPort: 80
          EOF
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Service
          metadata:
            name: customdevfile-service
          spec:
            type: ClusterIP
            selector:
              app: customdevfile
            ports:
              - port: 80
                targetPort: 80
          EOF
          cat <<EOF | kubectl apply -f -
          apiVersion: extensions/v1beta1
          kind: Ingress
          metadata:
            annotations:
              kubernetes.io/ingress.class: nginx
            name: custom-devfile
          spec:
            rules:
            - host: custom-devfile.$(minikube ip).nip.io
              http:
                paths:
                - backend:
                    serviceName: customdevfile-service
                    servicePort: 80
                  path: /
                  pathType: ImplementationSpecific
          EOF
          while [[ $(kubectl get pods -l app=customdevfile -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
          DEPLOY_POD_NAME=$(kubectl get pods -l app=customdevfile  -o 'jsonpath={...metadata.name}')
          echo "this is a running example of devfile" > foo.bar
          kubectl cp foo.bar $DEPLOY_POD_NAME:/usr/local/apache2/htdocs
          curl http://custom-devfile.$(minikube ip).nip.io/foo.bar
      - name: Run Happy Path tests
        id: happy-path-tests
        uses: benoitf/happy-path-tests-action@main
        with:
          che-url: ${{ steps.setup-che.outputs.che-url }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifacts
        if: ${{ always() }}
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: che/tests/e2e/report
      - name: Wait 1hour before shutting down instance
        if: ${{ failure() }}
        run: sleep 1h
