name: che-install
on: push
jobs:
  install:
    name: setup che
    runs-on: ubuntu-20.04
    steps:
      - name: Check before
        run: |
          echo "path is $PATH"
          echo "before, minikube version is"
          minikube version
      - name: Setup che
        id: setup-che
        uses: benoitf/che-install-gh-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: |
          echo "after, minikube version is"
          minikube version
          echo "list nodes with kubectl"
          kubectl get nodes
          echo "che URL is ${{ steps.setup-che.outputs.che-url }}"
          echo "che token is ${{ steps.setup-che.outputs.che-token }}"
          echo "che token is ${{ steps.setup-che.outputs.che-token }}"
          echo "create workspace and start it..."
          chectl workspace:create --start --access-token ${{ steps.setup-che.outputs.che-token }} --devfile=https://gist.githubusercontent.com/benoitf/6f2c761690646c930ea728e85054e43c/raw/620e0fca2911f62534007ca21769eee966ca9649/devfile-projects.yaml
          echo "workspace started"
          
