name: che-install

on: push

# on: #[push]

jobs:
  install:
    name: setup che
    runs-on: ubuntu-20.04
    steps:
      - name: Check before
        run: |
          echo "path is $PATH"
      - name: Setup che
        uses: benoitf/che-install-gh-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check
        run: |
          echo "list /usr/local/bin/"
          ls -la /usr/local/bin/        
          echo "list nodes with kubectl"
          kubectl get nodes
          
