name: che-install
on: push
jobs:
  install:
    name: setup che
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Launch Tests
        id: launch-tests
        run: |
          yarn
          yarn run test
      