name: che-install
on: push
jobs:
  install:
    name: setup che
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Record Display
        id: record-display
        run: |
           sudo apt-get update
           sudo apt-get install -y ffmpeg x11-apps
           export kill_ffmpeg() {
             echo "Killing ffmpeg with PID=$1"
             kill -2 "$1"
             echo "wait pid..."
             wait "$1" || echo "wait finished"
             echo "done"
             mkdir -p /tmp/e2e/report/
             echo "copy"
             cp /tmp/ffmpeg_report/* /tmp/e2e/report/
             return 0
           }
           mkdir -p /tmp/ffmpeg_report
           # export DISPLAY=:99
           # sudo Xvfb -ac :99 -screen 0 1280x1024x24 &
           # nohup ffmpeg -y -video_size 1920x1080 -framerate 24 -f x11grab -i :99.0 /tmp/ffmpeg_report/output.mp4 2> /tmp/ffmpeg_report/ffmpeg_err.txt > /tmp/ffmpeg_report/ffmpeg_std.txt & 
           export DISPLAY=':20'
           Xvfb :20 -screen 0 1920x1080x24 > /dev/null 2>&1 &
           nohup ffmpeg -y -video_size 1920x1080 -framerate 24 -f x11grab -i :20.0 /tmp/ffmpeg_report/output.mp4 2> /tmp/ffmpeg_report/ffmpeg_err.txt > /tmp/ffmpeg_report/ffmpeg_std.txt &
           FFMPEG_PID=$!
           echo "ffmpeg pid is ${FFMPEG_PID}"
           echo "::set-output name=ffmpeg-pid::${FFMPEG_PID}"
           trap kill_ffmpeg 2 15
           echo "ffmpeg error:"
           xclock&
           sleep 5
           cat /tmp/ffmpeg_report/ffmpeg_err.txt || echo "no error"
           echo "ffmpeg output:"
           cat /tmp/ffmpeg_report/ffmpeg_std.txt || echo "no stdout"
      - name: End Record Display
        id: end-record-display
        run: |
           kill_ffmpeg ${{ steps.record-display.outputs.ffmpeg-pid}}
      - name: upload artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: /tmp/e2e/report/
