name: che-install

on: push

jobs:
  install:
    name: setup che
    runs-on: ubuntu-20.04
    steps:
      - name: Check before
        run: |
          echo "path is $PATH"
          echo "before, minikube version is"
          minikube version
      - name: Setup che
        uses: benoitf/che-install-gh-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check
        run: |
          echo "after, minikube version is"
          minikube version
          echo "list nodes with kubectl"
          kubectl get nodes
          
