#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: minikube start

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  minikube:
    runs-on: ubuntu-20.04
    steps:
      - name: Start minikube
        id: run-minikube
        uses: che-incubator/setup-minikube-action@next
